# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [73]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [74]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) !

In [75]:
print(np.__version__)
print(np.__config__)
np.show_config # XXXXXXXXXXXXXXXXXXXXXX
# what is the difference between show_config, __config__ ?
hint(2)

2.3.3
<module 'numpy.__config__' from '/home/abdulrahman/code/numpy_practice/.venv/lib/python3.12/site-packages/numpy/__config__.py'>
hint: np.__version__, np.show_config)


#### 3. Create a null vector of size 10 (★☆☆)

In [76]:
print(np.zeros(10))
hint(3)
answer(3)

# isn't it called a null vector? why it contains a number 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
hint: np.zeros
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆) !

In [77]:
print(np.zeros(10).size) # XXXXXXXXXXXXXXXXX - this is not in "Memory"
answer(4)

print(np.zeros(10).size * np.zeros(10).itemsize)
print(np.zeros(10).nbytes)

10
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

# Simpler alternative
print("%d bytes" % Z.nbytes)
80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆) !

In [78]:
print(np.add.__doc__) # XXXXXXXXXXXX - not in Bash
answer(5)

# !python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [79]:
vec = np.zeros(10)
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [80]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆) !

In [81]:
# vec[-1:0:-1] # where is the first element ?! # XXXXXXXXX

vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [82]:
vec = np.arange(9).reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) !

In [83]:
# vec = np.array([1,2,0,0,4,0])
# vec[vec != 0] # XXXXXXXXXXXXX -> this will get the values themselves not the indices

np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) !

In [84]:
np.identity(3) # also: np.eye(N, M=None, k=0, dtype=None) -> it's more versatile
# N = rows, M = cols, k = diagonal position.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [85]:
np.random.randn(3,3,3)

array([[[-0.00892227,  0.95401662, -1.0756163 ],
        [ 1.97862784,  1.1851392 , -0.70632049],
        [ 0.56189056, -1.3824538 , -1.16888291]],

       [[-0.40427993, -0.0364589 ,  0.75496165],
        [-0.40874848, -0.93743946, -1.33233375],
        [-2.6583385 , -0.88363129,  0.05307463]],

       [[ 0.59265115,  0.364102  ,  0.75014745],
        [-1.09291793,  0.9409686 ,  1.25515806],
        [ 0.40038701,  0.79900964, -1.32796224]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [86]:
vec = np.random.randn(10,10)
print(vec)
print(vec.max(), vec.min())

[[-1.05750826e+00  1.71198074e+00 -6.97965971e-02 -9.92228411e-01
   1.23808560e+00  1.05543135e+00 -1.60945851e+00  9.45796503e-01
   6.66120118e-01 -2.10425532e+00]
 [-6.12780865e-02  2.84751711e-02  9.47264234e-01 -5.71471516e-01
   1.71392452e+00  4.76782157e-01  9.06968878e-01  4.05003671e-01
  -1.07490277e+00 -8.19459461e-01]
 [ 4.61779131e-01  6.47398613e-01 -4.88843183e-01 -3.52743949e-01
  -8.87190074e-01 -5.00049509e-01  1.12953209e+00  2.55976465e-01
  -1.26977411e+00  7.97622791e-01]
 [-2.85699751e-01  8.10277998e-01 -2.79606424e-03 -1.41150304e-01
  -9.14097353e-01 -4.37031995e-01  6.10064405e-01  8.01979953e-01
  -1.13789531e+00 -1.66419497e-01]
 [-9.02882350e-01 -7.79648302e-01 -2.84546361e-01 -1.39768909e+00
   1.54948256e+00 -1.01911088e-03  5.24428583e-01  1.42203777e+00
  -1.08349777e+00  9.86644609e-01]
 [-4.57443970e-01  3.15323034e-02  1.03506562e+00  1.20510241e+00
  -3.91083103e-01  1.87612839e+00  1.31348533e+00  6.57586910e-01
  -7.45621641e-01 -5.31884218e-01

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [87]:
np.random.randn(30).mean()

np.float64(-0.028679131635917943)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) !

In [88]:
vec = np.ones([10,10])

vec[1:-1,1:-1] = 0

vec

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) !

In [89]:
# ??

vec = np.ones([10,10])
vec = np.pad(vec, pad_width=1, mode='constant', constant_values=[0])
vec

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) !
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [90]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) !

In [91]:
vec = np.zeros([5,5])

vec[4,0:4] = [1,2,3,4]

vec

# another solution: 
np.diag(1+np.arange(4), k=-1) 
# 1. this first creates a diagonal below the original one (at k=0) 
# 2. the content of it is [1,2,3,4] which is equal to (1 + np.arange(4))
# 3. the size of the array is (5*5) because the diagonal we created at (k=-1) have 4 elements so the original one will have 5 elements
# 4. the rest of the elements are zero default

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) ! 

In [92]:
# ??
vec = np.zeros([8,8])
vec[1::2, ::2] = 1
vec[::2, 1::2] = 1

vec


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [93]:
vec = np.zeros([6,7,8])

flat = vec.flatten()

flat[99] = 6

vec = flat.reshape(6,7,8)

np.where(vec == 6)


# another solution: 
np.unravel_index(99,(6,7,8)) # finding the corresponding index to a flat index in a multidimensional shape.

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [94]:
np.tile([0,1], [8,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [95]:
val = np.random.randn(5,5)

print((val - val.min())/(val.max() - val.min()) )

[[0.56774407 0.63600497 0.39604469 0.23695596 0.23901285]
 [0.14137516 0.65835465 0.24654251 0.44144836 0.39063396]
 [0.30501921 0.03590001 0.         0.37547027 0.29695231]
 [0.3683487  0.24594569 0.21494084 0.50310397 0.56158412]
 [0.22979119 0.33466265 0.00776065 1.         0.70894157]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [96]:
# !
color = np.dtype([
    ('R', 'u1'),
    ('G', 'uint8'),
    ('B', 'uint8'),
    ('A', 'uint8')
])
# u1 = uint8

colors = np.empty(3, dtype=color)

colors

array([(199, 140, 56, 59), (  0,   0,  0,  0), (  0,   0,  0,  0)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [97]:
val = np.random.randint(1,10, [5,3]) 
val2 = np.random.randint(1,10, [3,2])

print(val)

print(val2)

val @ val2 #!

[[9 8 8]
 [2 2 2]
 [7 6 9]
 [4 8 1]
 [2 7 4]]
[[6 8]
 [1 6]
 [4 5]]


array([[ 94, 160],
       [ 22,  38],
       [ 84, 137],
       [ 36,  85],
       [ 35,  78]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [98]:
val = np.arange(10)

val[4:8] = 10 - val[4:8]

val

# answer(25)
# # Author: Evgeni Burovski

# Z = np.arange(11)
# Z[(3 < Z) & (Z < 8)] *= -1 # !
# print(Z)

array([0, 1, 2, 3, 6, 5, 4, 3, 8, 9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [99]:
14 # !
15 # !

15

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [100]:
# !

I = 3
2 << I >> 2
I <- I # = I < - I

answer(27)
Z = 3
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
27
4
False
3j
3.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [101]:
# !
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_6222/604574712.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_6222/604574712.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_6222/604574712.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [102]:
answer(29) # I don't understand the first answer

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [103]:
answer(30) # ok !

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [104]:
# with np.errstate(all="ignore"): # ! (that's a context manager)
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [105]:
# I think so.

np.sqrt(-1) == np.emath.sqrt(-1)

# it's wrong ! why?

# np.sqrt(-1) # floating number output (nan)
# np.emath.sqrt(-1) # complex number output (1j)


# 🧮 What is numpy.lib.scimath?
# The module is officially called numpy.lib.scimath. It's often imported under the convenient alias np.emath. Its purpose is to provide versions of mathematical functions that behave more usefully when dealing with complex numbers than the standard NumPy functions.

# The key difference is in how they handle inputs that would be invalid for real numbers. For example, what should the function do if you try to take the square root of a negative number?

/tmp/ipykernel_6222/3595560445.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [106]:
np.datetime64('now') # wow that's correct !
np.datetime64('now') - np.timedelta64(1,'D') # yesterday
np.datetime64('now') + np.timedelta64(1,'D') # tomorrow

np.datetime64('2025-09-29T19:49:03')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [107]:
first = np.datetime64('2016-07-01')
while np.datetime64(first, 'M').astype(int) % 12 + 1 == 7:
    print(first)
    first+=np.timedelta64(1,'D')

answer(34)

dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]') # the 'D' symbol is important here.
print(dates)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [108]:
# KEY LEARNING SUMMARY FROM NUMPY IN-PLACE OPERATIONS:

# 1. MEMORY MANAGEMENT
# - Normal operations (A + B) create new arrays each time
# - In-place operations (A += B) modify existing arrays, saving memory
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = A + B  # New array created: [5, 7, 9]
A += B     # A modified in-place: [5, 7, 9] (no new array)

# 2. OUT PARAMETER USAGE  
# - np.add(A, B, out=result) stores result in pre-allocated memory
result = np.empty_like(A)
np.add(A, B, out=result)  # result = [5, 7, 9] (no temporary)
np.add(A, B, out=A)       # A = [5, 7, 9] (overwrite original)

# 3. OPERATORS VS FUNCTIONS
# - Operators for simplicity, functions for control
C = A * B                    # Simple: [20, 35, 54]  
np.multiply(A, B, out=A)     # Controlled: A = [20, 35, 54]
np.multiply(A, B, where=[True,False,True])  # Conditional

# 4. TEMPORARY VARIABLE STRATEGY
# - One copy avoids multiple intermediates
A = np.array([1, 2, 3], dtype=float); B = np.array([4, 5, 6])
temp = A.astype(float)     # temp = [1, 2, 3] # without the .astype() -> the expression (Temp = A) will create an alias not a copy and when you multiply it by a fraction (.5) it will raise an error
A += B              # A = [5, 7, 9] 
temp *= -0.5        # temp = [-0.5, -1, -1.5]
A *= temp           # A = [-2.5, -7, -13.5] (only 3 arrays total)

# 5. EXPRESSION EXECUTION FLOW
# - Complex expressions create hidden temporaries
result = ((A + B) * (-A / 2))
# Actually creates: temp1=A+B, temp2=-A, temp3=temp2/2, result=temp1*temp3
# Total: 4 new arrays instead of 1!

# 6. EINSTEIN SUMMATION (EINSUM)
# - Compact notation for complex operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.einsum('ij,jk->ik', A, B)  # Matrix multiplication: [[19, 22], [43, 50]]

# 7. PERFORMANCE TRADEOFFS
# - Readable code vs Memory efficiency
# result = A + B - C * D  # Readable but creates 3 temporaries
# vs
# result = A.copy(); result += B; temp = C.copy(); temp *= D; result -= temp  # Efficient but complex

answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [109]:
arr = np.random.uniform(0,10, 10)
print((arr//1))
print(np.floor(arr))
print(np.trunc(arr))
print((arr - arr%1))
print(arr.astype(int))
print(arr)

answer(36)

[2. 1. 4. 2. 5. 4. 0. 6. 4. 6.]
[2. 1. 4. 2. 5. 4. 0. 6. 4. 6.]
[2. 1. 4. 2. 5. 4. 0. 6. 4. 6.]
[2. 1. 4. 2. 5. 4. 0. 6. 4. 6.]
[2 1 4 2 5 4 0 6 4 6]
[2.09714651 1.44737173 4.94664513 2.29802938 5.5255337  4.52922393
 0.15253253 6.73731753 4.27345468 6.67075995]
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [110]:
print(np.ones([5,5]) * np.arange(5)) 


answer(37)

print(np.zeros([5,5]) + np.arange(5)) # just like my solution
print(10*'#')
print(np.tile(np.arange(5), [5,1]))

# both np.ones, np.zeros produce floating point numbers

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
##########
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [111]:
def fun():
    for i in range(10):
        yield i
# np.array(fun()) # that's wrong

print(np.fromiter(fun(), dtype=float)) # adding ", count=-1" doesn't affect the result?

answer(38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [112]:
print(np.random.uniform(0,1, 10)) # is this actually excluding 0, 1 ?

answer(39)

print(np.linspace(0,1,11, endpoint=False)[1:])
# linspace produces an array that have equal difference between its consequetive elements
# the endpoint=False part is for excluding the "1" from the array
# the [1:] part is for excluding the "0" and therefore we need another element to make them = 10 elements so we produce 11.

print(np.linspace(0,1,12)[1:-1]) # the same result as above

[0.66394731 0.19978094 0.25376474 0.31111749 0.56372564 0.49486772
 0.43967707 0.04970433 0.14344668 0.41401303]
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [113]:
r = np.random.rand(10); r.sort(); print(r)  # in place sorting

print( np.sort( np.random.rand(10) ) ) # returns a new sorted array

answer(40)

[0.0383309  0.1029921  0.12081183 0.27247547 0.27882051 0.28420502
 0.39844728 0.59198426 0.73720176 0.76235735]
[0.00467837 0.05216709 0.10986    0.35428319 0.44816201 0.52767304
 0.59043752 0.66620551 0.70660388 0.93179401]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [114]:
# I don't know !

answer(41)
print('#'*10)
print( np.add.reduce([3,10,3]) ) 

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)
##########
16


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [115]:
a = np.random.rand(10)
b = np.random.rand(10)

print( a == b )
print('#'*10)

answer(42)

print( np.allclose(a,b) )

print( np.array_equal(a,b) )

[False False False False False False False False False False]
##########
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [116]:
# what ?

# for more about the topic: https://note.nkmk.me/en/python-numpy-ndarray-immutable-read-only/

answer(43)

# another way = 
# z = np.zeros(10)
# z.setflags(write=False)
# z[1] = 1

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [117]:
original = np.random.randint(10, size=[10,2])
print(original)
print('#'*10)

# useful: https://github.com/numpy/numpy/issues/5228

# for example: 

# def cart2pol(x, y):
#     """Converts Cartesian coordinates to polar coordinates."""
#     rho = np.hypot(x, y)
#     phi = np.arctan2(y, x)
#     return rho, phi

# def pol2cart(rho, phi):
#     """Converts polar coordinates to Cartesian coordinates."""
#     x = rho * np.cos(phi)
#     y = rho * np.sin(phi)
#     return x, y

# print(original[:,1]) # getting all the rows but only the second column (number: 1)
# we use arctan2 not arctan because it have better handling for dividing by zero issues

answer(44)

[[6 0]
 [1 8]
 [2 9]
 [3 3]
 [1 0]
 [6 1]
 [0 6]
 [3 6]
 [0 2]
 [2 8]]
##########
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [118]:
arr = np.random.randint(10,size=[10])
print(arr)
print('#'*10)

arr[ np.where(arr == arr.max())[0] ] = 0

print(arr)

answer(45)

# so, arr.argmax() = np.where(arr == arr.max())[0]

[3 8 7 6 0 9 0 6 9 6]
##########
[3 8 7 6 0 0 0 6 0 6]
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [119]:
arr = np.array([[0,0], [0,1], [1,0], [1,1]])
print(arr)

answer(46)

arr = np.zeros((5,5), [('x', float), ('y', float)]) # naming columns
print(arr)
print(arr['x'], arr['y'], sep='\n')
print('#'*10)

arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5)) # creating all possible combinations between the two 1D arrays (np.linspace) to create one 2D array.

print(arr)
print(arr['x'], arr['y'], sep='\n')


# first, the question can be solved without specifying exactly 5 points in each direction but OK !
# second, I've learned that I can name columns for a numpy array !
# third, the 'meshgrid' function can be used to create a 2D array with all possbile combinations between two 1D arrays.

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)
[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
##########
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [120]:
x = np.array([1,2,3])
y = np.array([4,5,6])


C = np.zeros((3,3), [('x', float), ('y', float)])
C['x'], C['y'] = np.meshgrid(x,y)
C = 1 / (C['x'] - C['y'])
print(C, '#'*10, sep='\n')

answer(47)

X = np.array([1,2,3])
Y = np.array([4,5,6])
print(X,Y)
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-0.33333333 -0.5        -1.        ]
 [-0.25       -0.33333333 -0.5       ]
 [-0.2        -0.25       -0.33333333]]
##########
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))
[1 2 3] [4 5 6]
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]
0.00046296296296296146


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [137]:
answer(48)

types = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]
types_f = [np.float16, np.float32, np.float64]
for dtype in types:
    print(np.iinfo(dtype))
for dtype in types_f:
    print(np.finfo(dtype))
    
print(np.iinfo(np.intp).max, np.iinfo(np.uintp).max, sep='\n')

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Ma

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
print(np.zeros([40,40])) # the default threshold is 1000

answer(49)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


In [ ]:
np.set_printoptions(threshold=float('inf')) # = np.inf = sys.maxsize
print(np.zeros([40,40]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [151]:
arr = np.random.rand(10)
value = 4.5
diff = np.abs(arr - value)
print(arr[diff.argmin()]) # not min() -> argmin is the index while min is the value

0.9322083410112443


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)