# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) !

In [3]:
print(np.__version__)
print(np.__config__)
np.show_config # XXXXXXXXXXXXXXXXXXXXXX
# what is the difference between show_config, __config__ ?
hint(2)

2.3.3
<module 'numpy.__config__' from '/home/abdulrahman/code/numpy_practice/.venv/lib/python3.12/site-packages/numpy/__config__.py'>
hint: np.__version__, np.show_config)


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
print(np.zeros(10))
hint(3)
answer(3)

# isn't it called a null vector? why it contains a number 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
hint: np.zeros
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆) !

In [5]:
print(np.zeros(10).size) # XXXXXXXXXXXXXXXXX - this is not in "Memory"
answer(4)

print(np.zeros(10).size * np.zeros(10).itemsize)
print(np.zeros(10).nbytes)

10
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

# Simpler alternative
print("%d bytes" % Z.nbytes)
80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆) !

In [6]:
print(np.add.__doc__) # XXXXXXXXXXXX - not in Bash
answer(5)

# !python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vec = np.zeros(10)
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆) !

In [9]:
# vec[-1:0:-1] # where is the first element ?! # XXXXXXXXX

vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
vec = np.arange(9).reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) !

In [11]:
# vec = np.array([1,2,0,0,4,0])
# vec[vec != 0] # XXXXXXXXXXXXX -> this will get the values themselves not the indices

np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) !

In [12]:
np.identity(3) # also: np.eye(N, M=None, k=0, dtype=None) -> it's more versatile
# N = rows, M = cols, k = diagonal position.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.randn(3,3,3)

array([[[ 1.49558288, -1.21946168,  1.8326393 ],
        [-0.53364456,  0.1838044 , -1.41976895],
        [-1.65900742, -0.64142044, -2.00963966]],

       [[-0.77688145,  0.50759785, -0.44331721],
        [-0.1809628 ,  0.12458787,  0.88529759],
        [-0.99119847, -2.00043593, -0.72732074]],

       [[-0.82095658, -0.01736203,  0.7259521 ],
        [ 1.22488727,  0.77694573,  1.01098135],
        [ 0.39912778, -0.13776161, -1.29295535]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
vec = np.random.randn(10,10)
print(vec)
print(vec.max(), vec.min())

[[-0.81467621 -1.34793412  0.27194844 -0.47439906 -0.17777922 -0.71948651
  -0.69186506 -0.42236768  0.10105972  1.03379651]
 [-0.21455668 -0.37639683 -0.74808269  0.09120035  0.03555956 -0.55894822
   0.1561278   2.16536504 -0.58733949 -1.33858825]
 [ 1.82946242  0.14551829  0.73165699 -0.30747714  0.25377629  1.10321113
  -0.67707079 -1.48753261  0.46456097 -2.60371412]
 [ 1.64164468 -1.00747819  0.56957489 -0.13336251 -0.38867338  1.05528542
  -1.09297961 -1.69874852 -1.02003276 -1.23208368]
 [ 0.36353398  1.2194036   0.75703     0.38721316 -0.17805022  0.9108984
  -0.10696353 -2.2339794  -0.58364679 -0.56720002]
 [ 0.00541508 -1.01085383 -0.12118436  1.28671573  0.87233469 -1.12926939
  -1.02721904  0.35966915  1.21963951 -1.44176881]
 [ 1.07405421  0.02508626  0.44182323  0.63374667  0.67011288  0.31666908
   0.82007317 -0.34551849 -0.79706066  0.2594562 ]
 [-0.67912723  0.15458055 -1.08099632 -1.10548527 -1.27332145  0.84814753
  -0.62141191 -0.880416   -0.98716946 -0.18255348]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.randn(30).mean()

np.float64(0.02364936369725041)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) !

In [16]:
vec = np.ones([10,10])

vec[1:-1,1:-1] = 0

vec

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) !

In [17]:
# ??

vec = np.ones([10,10])
vec = np.pad(vec, pad_width=1, mode='constant', constant_values=[0])
vec

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) !
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) !

In [19]:
vec = np.zeros([5,5])

vec[4,0:4] = [1,2,3,4]

vec

# another solution: 
np.diag(1+np.arange(4), k=-1) 
# 1. this first creates a diagonal below the original one (at k=0) 
# 2. the content of it is [1,2,3,4] which is equal to (1 + np.arange(4))
# 3. the size of the array is (5*5) because the diagonal we created at (k=-1) have 4 elements so the original one will have 5 elements
# 4. the rest of the elements are zero default

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) ! 

In [20]:
# ??
vec = np.zeros([8,8])
vec[1::2, ::2] = 1
vec[::2, 1::2] = 1

vec


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
vec = np.zeros([6,7,8])

flat = vec.flatten()

flat[99] = 6

vec = flat.reshape(6,7,8)

np.where(vec == 6)


# another solution: 
np.unravel_index(99,(6,7,8)) # finding the corresponding index to a flat index in a multidimensional shape.

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
np.tile([0,1], [8,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
val = np.random.randn(5,5)

print((val - val.min())/(val.max() - val.min()) )

[[0.68085732 0.8513357  1.         0.80499099 0.7839986 ]
 [0.50335779 0.85399548 0.75398608 0.80797862 0.97393529]
 [0.64282963 0.47169903 0.64416694 0.60773486 0.5603468 ]
 [0.6856067  0.         0.82552788 0.39488144 0.35986437]
 [0.9053418  0.65306497 0.74959163 0.62943749 0.72095816]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
# !
color = np.dtype([
    ('R', 'u1'),
    ('G', 'uint8'),
    ('B', 'uint8'),
    ('A', 'uint8')
])
# u1 = uint8

colors = np.empty(3, dtype=color)

colors

array([(74, 179, 0, 0), ( 0,   0, 0, 0), ( 0,   0, 0, 0)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
val = np.random.randint(1,10, [5,3]) 
val2 = np.random.randint(1,10, [3,2])

print(val)

print(val2)

val @ val2 #!

[[9 8 9]
 [3 3 2]
 [3 9 3]
 [4 2 1]
 [1 2 4]]
[[1 3]
 [4 9]
 [4 7]]


array([[ 77, 162],
       [ 23,  50],
       [ 51, 111],
       [ 16,  37],
       [ 25,  49]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
val = np.arange(10)

val[4:8] = 10 - val[4:8]

val

# answer(25)
# # Author: Evgeni Burovski

# Z = np.arange(11)
# Z[(3 < Z) & (Z < 8)] *= -1 # !
# print(Z)

array([0, 1, 2, 3, 6, 5, 4, 3, 8, 9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
14 # !
15 # !

15

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
# !

I = 3
2 << I >> 2
I <- I # = I < - I

answer(27)
Z = 3
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
27
4
False
3j
3.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
# !
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_192752/604574712.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_192752/604574712.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_192752/604574712.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
answer(29) # I don't understand the first answer

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
answer(30) # ok !

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
# with np.errstate(all="ignore"): # ! (that's a context manager)
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
# I think so.

np.sqrt(-1) == np.emath.sqrt(-1)

# it's wrong ! why?

# np.sqrt(-1) # floating number output (nan)
# np.emath.sqrt(-1) # complex number output (1j)


# 🧮 What is numpy.lib.scimath?
# The module is officially called numpy.lib.scimath. It's often imported under the convenient alias np.emath. Its purpose is to provide versions of mathematical functions that behave more usefully when dealing with complex numbers than the standard NumPy functions.

# The key difference is in how they handle inputs that would be invalid for real numbers. For example, what should the function do if you try to take the square root of a negative number?

/tmp/ipykernel_192752/3595560445.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
np.datetime64('now') # wow that's correct !
np.datetime64('now') - np.timedelta64(1,'D') # yesterday
np.datetime64('now') + np.timedelta64(1,'D') # tomorrow

np.datetime64('2025-10-02T05:28:47')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
first = np.datetime64('2016-07-01')
while np.datetime64(first, 'M').astype(int) % 12 + 1 == 7:
    print(first)
    first+=np.timedelta64(1,'D')

answer(34)

dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]') # the 'D' symbol is important here.
print(dates)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
# KEY LEARNING SUMMARY FROM NUMPY IN-PLACE OPERATIONS:

# 1. MEMORY MANAGEMENT
# - Normal operations (A + B) create new arrays each time
# - In-place operations (A += B) modify existing arrays, saving memory
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = A + B  # New array created: [5, 7, 9]
A += B     # A modified in-place: [5, 7, 9] (no new array)

# 2. OUT PARAMETER USAGE  
# - np.add(A, B, out=result) stores result in pre-allocated memory
result = np.empty_like(A)
np.add(A, B, out=result)  # result = [5, 7, 9] (no temporary)
np.add(A, B, out=A)       # A = [5, 7, 9] (overwrite original)

# 3. OPERATORS VS FUNCTIONS
# - Operators for simplicity, functions for control
C = A * B                    # Simple: [20, 35, 54]  
np.multiply(A, B, out=A)     # Controlled: A = [20, 35, 54]
np.multiply(A, B, where=[True,False,True])  # Conditional

# 4. TEMPORARY VARIABLE STRATEGY
# - One copy avoids multiple intermediates
A = np.array([1, 2, 3], dtype=float); B = np.array([4, 5, 6])
temp = A.astype(float)     # temp = [1, 2, 3] # without the .astype() -> the expression (Temp = A) will create an alias not a copy and when you multiply it by a fraction (.5) it will raise an error
A += B              # A = [5, 7, 9] 
temp *= -0.5        # temp = [-0.5, -1, -1.5]
A *= temp           # A = [-2.5, -7, -13.5] (only 3 arrays total)

# 5. EXPRESSION EXECUTION FLOW
# - Complex expressions create hidden temporaries
result = ((A + B) * (-A / 2))
# Actually creates: temp1=A+B, temp2=-A, temp3=temp2/2, result=temp1*temp3
# Total: 4 new arrays instead of 1!

# 6. EINSTEIN SUMMATION (EINSUM)
# - Compact notation for complex operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.einsum('ij,jk->ik', A, B)  # Matrix multiplication: [[19, 22], [43, 50]]

# 7. PERFORMANCE TRADEOFFS
# - Readable code vs Memory efficiency
# result = A + B - C * D  # Readable but creates 3 temporaries
# vs
# result = A.copy(); result += B; temp = C.copy(); temp *= D; result -= temp  # Efficient but complex

answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
arr = np.random.uniform(0,10, 10)
print((arr//1))
print(np.floor(arr))
print(np.trunc(arr))
print((arr - arr%1))
print(arr.astype(int))
print(arr)

answer(36)

[5. 3. 4. 8. 4. 3. 9. 2. 2. 0.]
[5. 3. 4. 8. 4. 3. 9. 2. 2. 0.]
[5. 3. 4. 8. 4. 3. 9. 2. 2. 0.]
[5. 3. 4. 8. 4. 3. 9. 2. 2. 0.]
[5 3 4 8 4 3 9 2 2 0]
[5.02097991 3.1026478  4.43901935 8.13581154 4.22037976 3.96067859
 9.55048748 2.95505712 2.20383309 0.134458  ]
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
print(np.ones([5,5]) * np.arange(5)) 


answer(37)

print(np.zeros([5,5]) + np.arange(5)) # just like my solution
print(10*'#')
print(np.tile(np.arange(5), [5,1]))

# both np.ones, np.zeros produce floating point numbers

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
##########
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def fun():
    for i in range(10):
        yield i
# np.array(fun()) # that's wrong

print(np.fromiter(fun(), dtype=float)) # adding ", count=-1" doesn't affect the result?

answer(38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
print(np.random.uniform(0,1, 10)) # is this actually excluding 0, 1 ?

answer(39)

print(np.linspace(0,1,11, endpoint=False)[1:])
# linspace produces an array that have equal difference between its consequetive elements
# the endpoint=False part is for excluding the "1" from the array
# the [1:] part is for excluding the "0" and therefore we need another element to make them = 10 elements so we produce 11.

print(np.linspace(0,1,12)[1:-1]) # the same result as above

[0.1223206  0.43385449 0.59471909 0.18293372 0.8471153  0.0711877
 0.6698354  0.30620489 0.08721694 0.98482689]
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
r = np.random.rand(10); r.sort(); print(r)  # in place sorting

print( np.sort( np.random.rand(10) ) ) # returns a new sorted array

# # np.argsort() - Returns indices that would sort array
# indices = np.argsort(arr)                    # [1, 3, 6, 0, 2, 4, 5]
# sorted_via_indices = arr[indices]            # Same as np.sort(arr)


# # Sort entire array flattened
# flat_sorted = np.sort(arr_2d, axis=None)     # [1, 1, 2, 3, 4, 5, 5, 6, 9]

answer(40)

[0.03386487 0.26180679 0.3664982  0.37083598 0.48304108 0.66253558
 0.68758279 0.78310776 0.83308262 0.94708341]
[0.32294341 0.43274831 0.49326125 0.69884365 0.74834015 0.78862827
 0.8736814  0.93715348 0.97404855 0.9825169 ]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
# I don't know !

answer(41)
print('#'*10)
print( np.add.reduce([3,10,3]) ) 

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)
##########
16


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [43]:
a = np.random.rand(10)
b = np.random.rand(10)

print( a == b )
print('#'*10)

answer(42)

print( np.allclose(a,b) )

print( np.array_equal(a,b) )

[False False False False False False False False False False]
##########
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
# what ?

# for more about the topic: https://note.nkmk.me/en/python-numpy-ndarray-immutable-read-only/

answer(43)

# another way = 
# z = np.zeros(10)
# z.setflags(write=False)
# z[1] = 1

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
original = np.random.randint(10, size=[10,2])
print(original)
print('#'*10)

# useful: https://github.com/numpy/numpy/issues/5228

# for example: 

# def cart2pol(x, y):
#     """Converts Cartesian coordinates to polar coordinates."""
#     rho = np.hypot(x, y)
#     phi = np.arctan2(y, x)
#     return rho, phi

# def pol2cart(rho, phi):
#     """Converts polar coordinates to Cartesian coordinates."""
#     x = rho * np.cos(phi)
#     y = rho * np.sin(phi)
#     return x, y

# print(original[:,1]) # getting all the rows but only the second column (number: 1)
# we use arctan2 not arctan because it have better handling for dividing by zero issues

answer(44)

[[7 9]
 [1 7]
 [0 3]
 [6 2]
 [4 5]
 [8 4]
 [0 1]
 [1 4]
 [9 8]
 [3 2]]
##########
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
arr = np.random.randint(10,size=[10])
print(arr)
print('#'*10)

arr[ np.where(arr == arr.max())[0] ] = 0

print(arr)

answer(45)

# so, arr.argmax() = np.where(arr == arr.max())[0]

[0 6 4 2 0 6 6 1 2 4]
##########
[0 0 4 2 0 0 0 1 2 4]
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
arr = np.array([[0,0], [0,1], [1,0], [1,1]])
print(arr)

answer(46)

arr = np.zeros((5,5), [('x', float), ('y', float)]) # naming columns - that's a structured array!
print(arr)
print(arr['x'], arr['y'], sep='\n')
print('#'*10)

arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5)) # creating all possible combinations between the two 1D arrays (np.linspace) to create one 2D array.

print(arr)
print(arr['x'], arr['y'], sep='\n')


# first, the question can be solved without specifying exactly 5 points in each direction but OK !
# second, I've learned that I can name columns for a numpy array !
# third, the 'meshgrid' function can be used to create a 2D array with all possbile combinations between two 1D arrays.

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)
[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
##########
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
x = np.array([1,2,3])
y = np.array([4,5,6])


C = np.zeros((3,3), [('x', float), ('y', float)])
C['x'], C['y'] = np.meshgrid(x,y)
C = 1 / (C['x'] - C['y'])
print(C, '#'*10, sep='\n')

answer(47)

X = np.array([1,2,3])
Y = np.array([4,5,6])
print(X,Y)
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-0.33333333 -0.5        -1.        ]
 [-0.25       -0.33333333 -0.5       ]
 [-0.2        -0.25       -0.33333333]]
##########
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))
[1 2 3] [4 5 6]
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]
0.00046296296296296146


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [49]:
answer(48)

types = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]
types_f = [np.float16, np.float32, np.float64]
for dtype in types:
    print(np.iinfo(dtype))
for dtype in types_f:
    print(np.finfo(dtype))
    
print(np.iinfo(np.intp).max, np.iinfo(np.uintp).max, sep='\n')

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Ma

#### 49. How to print all the values of an array? (★★☆)

In [50]:
print(np.zeros([40,40])) # the default threshold is 1000

answer(49)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


In [51]:
np.set_printoptions(threshold=float('inf')) # = np.inf = sys.maxsize
print(np.zeros([40,40]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
arr = np.random.rand(10)
value = 4.5
diff = np.abs(arr - value)
print(arr[diff.argmin()]) # not min() -> argmin is the index while min is the value

0.908255007438336


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [53]:
np.set_printoptions(threshold=1000) # = np.inf = sys.maxsize


arr = np.zeros((5,5), [('x', int), ('y', int)])
print(arr)

arr = np.zeros((128,128,128), [('r', int), ('g', int), ('b', int)])
print(arr)

answer(51)


# to make them in one array: Z = np.zeros(10, dtype = [ ('position', [ ('x', float, 1), ('y', float, 1)]),
                            #    ('color',    [ ('r', float, ('g', float, 1), ('b', float, 1)])])

[[(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]]
[[[(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  ...
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]]

 [[(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  ...
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) (0, 0, 0) (0, 0, 0)]
  [(0, 0, 0) (0, 0, 0) (0, 0, 0) ... (0, 0, 0) 

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [54]:
answer(52)

z = np.random.random((10,2))
x, y = np.atleast_2d(z[:,0], z[:,1])
d = np.sqrt( (x - x.T)**2 + (y - y.T)**2 )
print(d)

# no need to fully understand this !

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)
[[0.         0.65102594 0.9691771  0.28104163 0.7964405  0.95447122
  0.50650326 0.69476813 0.24598616 0.80308858]
 [0.65102594 0.         0.36893216 0.73936417 0.77875223 0.39397157
  0.7622105  0.04548783 0.48513731 0.40253659]
 [0.9691771  0.36893216 0.         0.97747163 0.77153211 0.082489
  0.90845627 0.34437862 0.75455886 0.30109516]
 [0.28104163 0.73936417 0.97747163 0.         0.58017105 0.93989493
  0.24749748 0.78463962 0.25695335 0.74002276]
 [0.7964405  0.77875223 0.77153211 0.58017105 0.         0.69719966
  0.34633107 0.80841961 0.58334391 0.47180223]
 [0.95447122 0.39397157 0.082489   0.93989493 0.69719966 0.
  0.85348196 0.37786707 0.72943986 0.23205306]
 [0.50650326 0.7622105  0.908

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [55]:
z = np.arange(10, dtype=np.float32)
z.dtype = np.int32
z.dtype

answer(53)

# 1. ORIGINAL ARRAY: [1.0, 2.7, 4.5] as float32
#    Memory: [3F800000, 402CCCCD, 40900000] (float bit patterns)

# 2. DANGEROUS: z.dtype = np.int32
#    SAME memory, just reinterpreted: [1065353216, 1075000115, 1083179008]
#    WRONG values - no actual conversion!

# 3. SAFE BUT MEMORY-HEAVY: z.astype(np.int32)  
#    CREATES NEW array: [1, 2, 4]
#    ORIGINAL memory unchanged, NEW memory allocated

# 4. MEMORY-EFFICIENT: Y = Z.view(np.int32); Y[:] = Z
#    Step 1: Y views SAME memory as int32: [1065353216, 1075000115, 1083179008]
#    Step 2: Y[:] = Z OVERWRITES memory with converted values: [1, 2, 4]
#    Result: Same memory reused, proper conversion, no extra allocation

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
f = np.genfromtxt('file.csv', delimiter=',')
# =============================================
# SUMMARY: READING FILES IN NUMPY
# =============================================

# 1. For simple text files (CSV, TSV):
# ------------------------------------
# data = np.loadtxt('file.txt')                    # Space-separated
# data = np.loadtxt('file.csv', delimiter=',')     # CSV files
# data = np.loadtxt('file.csv', delimiter=',', skiprows=1, dtype=int)  # Skip header, specify type
# data = np.loadtxt('file.csv', delimiter=',', usecols=(0, 2))         # Select specific columns

# 2. For text files with missing values:
# --------------------------------------
# data = np.genfromtxt('file.csv', delimiter=',')           # Auto-fill missing with NaN
# data = np.genfromtxt('file.csv', delimiter=',', filling_values=0)  # Fill missing with 0
# data = np.genfromtxt('file.csv', delimiter=',', usemask=True)      # Create masked array

# 3. For NumPy binary files (.npy, .npz):
# ---------------------------------------
# array = np.load('data.npy')                                # Single array
# with np.load('archive.npz') as data:                       # Multiple arrays
#     array1 = data['array1']
#     array2 = data['array2']

# 4. For memory-mapped large arrays:
# ----------------------------------
# large_array = np.load('large_array.npy', mmap_mode='r')

# 5. For raw binary data (use with caution):
# ------------------------------------------
# data = np.fromfile('binary_data.bin', dtype=np.float32)

# =============================================
# RECOMMENDATIONS:
# - Use .npy/.npz format for reliable storage
# - Avoid fromfile() for long-term storage
# - Use genfromtxt() for messy data with missing values
# =============================================

answer(55)


Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


In [57]:
# =============================================
# SUMMARY: CREATING NUMPY .NPY/.NPZ FILES
# =============================================

# 1. Saving single array to .npy:
# -------------------------------
# np.save('filename.npy', array)           # Saves single array efficiently
# loaded_array = np.load('filename.npy')   # Load it back

# 2. Saving multiple arrays to .npz:
# ----------------------------------
# np.savez('archive.npz', key1=array1, key2=array2)  # Uncompressed
# np.savez_compressed('archive.npz', key1=array1, key2=array2)  # Compressed

# 3. Loading .npz files:
# ----------------------
# data = np.load('archive.npz')
# array1 = data['key1']                    # Access by key name
# array2 = data['key2']
# print(data.files)                        # List all keys

# =============================================
# CREATING CSV FILES FROM NUMPY
# =============================================

# 1. Basic CSV export:
# --------------------
# np.savetxt('data.csv', array, delimiter=',')           # Comma-separated
# np.savetxt('data.tsv', array, delimiter='\t')          # Tab-separated

# 2. CSV with header and formatting:
# ----------------------------------
# np.savetxt('data.csv', array, delimiter=',', 
#            header='col1,col2,col3',        # Column names
#            fmt='%.2f',                     # Float formatting (2 decimal places)
#            comments='')                    # Remove '#' from header

# 3. CSV with specific data types:
# --------------------------------
# np.savetxt('data.csv', array, delimiter=',', 
#            fmt='%d')                       # Integer format

# 4. For structured arrays with mixed data:
# -----------------------------------------
# Use pandas: pd.DataFrame(array).to_csv('data.csv', index=False)

# =============================================
# QUICK EXAMPLES:
# =============================================

# Create and save arrays
# array = np.random.rand(5, 3)
# np.save('data.npy', array)                           # Binary format
# np.savetxt('data.csv', array, delimiter=',')         # CSV format

# Create structured data example
# structured_array = np.array([(1, 2.5, 'A'), (2, 3.7, 'B')], 
#                            dtype=[('id', 'i4'), ('value', 'f4'), ('label', 'U1')])
# Use pandas for mixed data types: 
# pd.DataFrame(structured_array).to_csv('structured.csv', index=False)

# =============================================
# KEY POINTS:
# - Use .npy/.npz for NumPy-to-NumPy (fast, preserves everything)
# - Use CSV for sharing/exchanging data with other programs
# - Use pandas for complex/mixed data types in CSV
# =============================================

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [58]:
arr = np.random.randint(1, 10, 10)
size =0
for i in np.ndenumerate(arr): # if you want only indexes use: ndindex() instead
    print(i[1]); size+= i[1]
print(size)

answer(55)

9
4
3
7
9
7
5
9
1
8
62
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [59]:
print(np.random.normal(loc=0.0, scale=1.0, size=[100,2]))

answer(56)

# G(x,y) = exp(-(x² + y²) / (2σ²)) is equivalent to this

[[ 0.61130162 -1.29914203]
 [-0.83603241  1.46496407]
 [-0.66573218 -1.43538996]
 [-0.27509469  0.58112922]
 [ 0.58898543  0.19178536]
 [-1.7278542  -0.81502611]
 [-1.99027342 -0.06229929]
 [-0.49339592 -0.67153132]
 [-0.93072041  0.34462221]
 [ 0.43012358  0.99872126]
 [ 0.14120383 -0.2115948 ]
 [-1.90194523  0.58659996]
 [-0.96418872 -1.59709527]
 [-1.09409271 -0.36830964]
 [-0.54680908  0.47392104]
 [-1.78006191 -0.96174762]
 [-0.89516191  1.5475055 ]
 [ 2.44534919 -1.36819769]
 [-1.22333264  0.12372018]
 [-0.53256196 -0.6936627 ]
 [ 0.50930507  0.41079114]
 [-0.06078476 -0.48543915]
 [-0.47698992 -0.31181067]
 [ 1.97245959 -0.59380631]
 [ 0.19681685  0.55938231]
 [-0.20694041  0.1863611 ]
 [ 0.50304813  0.44269082]
 [-2.99575859 -0.10843693]
 [-0.12650338  0.9447095 ]
 [ 0.51716225 -0.70288478]
 [ 0.68185146 -0.00696534]
 [ 1.19318498 -0.33961525]
 [ 0.19634784  0.95706548]
 [ 0.60787225  0.84041268]
 [-0.49129038  0.48225679]
 [ 0.78980004  0.76265242]
 [-0.40417285 -1.12031756]
 

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [60]:
answer(57)

arr = np.full(shape=[10,10], fill_value=0) # creating an array with a custom shape and default value
p = 3


# the following is useful for choosing a random number (size) of items from a max limit of (a)
# replace=False means that no choice can be chosen twice.
# in this case, we use this function to choose p (size) indicies from an array that have (arr.size=100) total indicies
# .
indicies = np.random.choice(a=arr.size, size=p, replace=False)
print(indicies)


# int this function np.put,  works with the random indicies we choosed, the values to put in them, and the array to make the changes to
# the value (v) column when we want 3 values for example can work with 1, 2, or 3 values normally!
# .
np.put(a=arr, ind=indicies, v=[20])
print(arr)


# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)
[28 64 90]
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [61]:
arr = np.random.rand(4,4)
l = []

# mean(axis=1) can replace all of the following
for i in range(arr.shape[1]): 
    l.append(arr[:,i].mean())

print(l)
print('#'*10)
print(arr)
print('#'*10)

answer(58)


old_arr = np.random.rand(5, 10)

# Recent versions of numpy
new_arr = old_arr - old_arr.mean(axis=1, keepdims=True)

# Older versions of numpy
new_arr = old_arr - old_arr.mean(axis=1).reshape(-1, 1)


print('#'*10)
print(old_arr)
print('#'*10)
print(new_arr)
# =============================================
# NUMPY keepdims=True - KEY POINTS
# =============================================

# 1. WHAT IT DOES:
# ---------------
# keepdims=True preserves array dimensions during reduction operations
# Without it: (5, 10) → mean(axis=1) → (5,)    # Dimension lost!
# With it:    (5, 10) → mean(axis=1, keepdims=True) → (5, 1)  # Dimension kept!

# 2. WHY IT MATTERS FOR BROADCASTING:
# -----------------------------------
# X.shape = (5, 10)
# 
# Without keepdims:
# mean = X.mean(axis=1)        # shape (5,) 
# Y = X - mean                 # ERROR! (5,10) vs (5,) - incompatible
#
# With keepdims:
# mean = X.mean(axis=1, keepdims=True)  # shape (5, 1)
# Y = X - mean                          # WORKS! (5,10) vs (5,1) - broadcasts

# 3. PRACTICAL EXAMPLES:
# ----------------------
# Standardization:
# normalized = (X - X.mean(axis=1, keepdims=True)) / X.std(axis=1, keepdims=True)

# Centering:
# centered = X - X.mean(axis=0, keepdims=True)  # Center columns

# 4. ALTERNATIVE WITHOUT keepdims:
# --------------------------------
# mean_manual = X.mean(axis=1).reshape(-1, 1)  # Manual reshaping needed
# Y_manual = X - mean_manual

# 5. BOTTOM LINE:
# ---------------
# Use keepdims=True for cleaner code and automatic broadcasting compatibility
# Especially useful with: mean(), sum(), max(), min(), std(), var()
# =============================================
# reshape(-1,1) means: keep the number of rows as it's but force the number of columns to be 1

[np.float64(0.3816672021652482), np.float64(0.5540999236452954), np.float64(0.28395722334342244), np.float64(0.4218849990614251)]
##########
[[0.4222663  0.94553192 0.11963564 0.68608056]
 [0.46634304 0.40213862 0.02687848 0.35052674]
 [0.30394559 0.2777105  0.65589494 0.61710273]
 [0.33411388 0.59101866 0.33341984 0.03382997]]
##########
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
##########
[[0.78694367 0.64699647 0.92530578 0.01320589 0.76688398 0.69555515
  0.76294776 0.8639195  0.59911153 0.83264299]
 [0.54194132 0.05555143 0.59587533 0.66995754 0.73848052 0.21708793
  0.71103394 0.36993867 0.5572484  0.98999613]
 [0.11287527 0.55204937 0.44912012 0.48446951 0.16147779 0.75692446
  0.75983896 0.1272983  0.45810126 0.9761964 ]
 [0.71329735 0.58084802 0.10281921 0.37075441 0.76325873 0.38558468
  0.17855557 0.5140961  0.52579517 0.781

#### 59. How to sort an array by the nth column? (★★☆)

In [62]:
arr = np.random.randint(0,10,[10,10])
print(arr)
print('#'*10)
n = 3
# arr.sort(axis=0, order=3)

answer(59)

print(arr[ arr[:,n].argsort() ]) # getting the indexes of the sorted nth column then "arr[sorted_column]" sort the whole array by it.

# =============================================
# NUMPY SORTING - COMPLETE SUMMARY
# =============================================

# 1. BASIC SORTING FUNCTIONS:
# ---------------------------
# sorted_arr = np.sort(arr)           # Returns sorted COPY (all dimensions)
# arr.sort()                          # In-place sort (modifies original)
# indices = np.argsort(arr)           # Returns indices that sort the array
# sorted_arr = arr[indices]           # Sort using indices

# 2. MULTI-DIMENSIONAL SORTING:
# -----------------------------
# np.sort(arr_2d, axis=0)            # Sort along ROWS (each column)
# np.sort(arr_2d, axis=1)            # Sort along COLUMNS (each row)  
# np.sort(arr_2d, axis=None)         # Flatten and sort entire array

# 3. PARTIAL SORTING (Efficient for top/bottom k):
# ------------------------------------------------
# 1. partial = np.partition(arr, k)      # Elements before k are smaller, after are larger
# 2. indices = np.argpartition(arr, k)   # Indices for partial sort
# 3. Get 3 largest elements:
    # Step 1: np.partition(arr, -3) - This rearranges the array so that the 3rd largest element 
    #   is in the 3rd position from the end, with all larger elements to its right
    # Step 2: [-3:] - This takes a slice of the last 3 elements from the rearranged array
    # Example: If arr = [5, 2, 8, 1, 9, 3, 7]
    #          np.partition(arr, -3) might give: [1, 2, 3, 5, 7, 8, 9]  
    #          Then [-3:] takes: [7, 8, 9] which are the 3 largest

# 4. SORTING ALGORITHMS (kind parameter):
# ---------------------------------------
# np.sort(arr, kind='quicksort')     # Fastest, not stable (DEFAULT)
# np.sort(arr, kind='mergesort')     # Stable (preserves equal element order)
# np.sort(arr, kind='heapsort')      # Good worst-case performance

# 5. STRUCTURED ARRAYS (sort by fields):
# --------------------------------------
# dt = [('name', 'U10'), ('age', int)]
# people = np.array([('Alice',25), ('Bob',20)], dtype=dt)
# by_age = np.sort(people, order='age')           # Sort by age field
# by_multi = np.sort(people, order=['age','name'])# Sort by multiple fields

# 6. SPECIAL DATA TYPES:
# ----------------------
# Complex: sorted by real part, then imaginary
# Strings: lexicographical order
# Custom: use argsort with custom key function

# 7. COMMON PATTERNS:
# -------------------
# Descending order: np.sort(arr)[::-1]
# Sort rows by column: data[data[:,0].argsort()]
# Get top k: arr[np.argpartition(arr, -k)[-k:]]
# Stable sort for complex cases: kind='mergesort'

# =============================================
# QUICK REFERENCE - WHEN TO USE WHAT:
# =============================================

# np.sort()        - Need sorted copy, any dimension
# .sort()          - In-place, memory efficient  
# np.argsort()     - Need sorting order for multiple arrays
# np.partition()   - Only care about top/bottom k elements (FAST)
# kind='mergesort' - When equal elements should keep original order
# axis parameter   - Control sorting direction in multi-dim arrays

# =============================================
# PERFORMANCE TIPS:
# =============================================
# - Use partition() instead of sort() for top/bottom k
# - quicksort is fastest for most cases
# - mergesort when stability matters
# - argsort + indexing for sorting multiple related arrays
# =============================================

[[3 7 8 0 7 4 5 1 6 8]
 [7 5 1 8 1 8 1 4 1 0]
 [4 9 0 9 7 0 7 5 5 6]
 [1 9 1 5 6 8 8 1 5 8]
 [9 2 9 3 7 5 5 3 2 2]
 [5 9 7 3 2 9 2 7 1 5]
 [7 4 5 1 6 5 4 0 0 6]
 [8 8 3 9 4 4 9 0 2 8]
 [7 6 2 3 0 1 9 2 7 9]
 [2 8 0 1 3 1 4 4 4 8]]
##########
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])
[[3 7 8 0 7 4 5 1 6 8]
 [7 4 5 1 6 5 4 0 0 6]
 [2 8 0 1 3 1 4 4 4 8]
 [9 2 9 3 7 5 5 3 2 2]
 [7 6 2 3 0 1 9 2 7 9]
 [5 9 7 3 2 9 2 7 1 5]
 [1 9 1 5 6 8 8 1 5 8]
 [7 5 1 8 1 8 1 4 1 0]
 [8 8 3 9 4 4 9 0 2 8]
 [4 9 0 9 7 0 7 5 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
print(f[f is None]) # wrong!

answer(60)

# =============================================
# CHECKING FOR NULL/NaN VALUES IN NUMPY ARRAYS
# =============================================

# 1. BASIC NaN CHECKING:
# ----------------------
# nan_mask = np.isnan(arr)            # Returns Boolean array (True where NaN exists)
# has_any_nan = np.any(np.isnan(arr)) # Returns True if ANY NaN found in array
# all_finite = np.all(np.isfinite(arr)) # Returns True if ALL elements are valid numbers

# 2. PRACTICAL EXAMPLES:
# ----------------------
# arr = np.array([1.0, 2.0, np.nan, 4.0])
# 
# np.isnan(arr)     → [False, False, True, False]  # See WHERE NaNs are
# np.any(np.isnan(arr)) → True                     # Check IF any NaN exists
# np.all(np.isfinite(arr)) → False                 # Check if ALL are valid numbers

# 3. IMPORTANT NOTES:
# -------------------
# - Integer arrays CANNOT contain NaN values (only works with Floats)
# - Use np.isnan(np.sum(arr)) for efficient yes/no checking
# - Use np.isnan(arr) to locate exact positions of NaNs
# - np.isfinite() also checks for infinite values (inf, -inf)

# 4. QUICK REFERENCE:
# -------------------
# "Is there any NaN?" → np.any(np.isnan(arr))
# "Where are the NaNs?" → np.isnan(arr)  
# "Are all values valid numbers?" → np.all(np.isfinite(arr))
# =============================================

print('#'*10)
# checking int 2D arrays for all-zero columns: ~arr.any(axis=0).any()
# checking float 2D arrays for None columns: np.isnan(arr).all(axis=0)
# .


[]
# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))
##########
[[1 1 2 0 1 2 0 0 0 1]
 [1 1 1 0 2 1 2 1 2 2]
 [2 2 1 1 0 2 2 0 2 1]]
[ True  True  True  True  True  True  True  True  True  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [92]:
answer(61)
arr = np.random.uniform(0,1,10)
value = 0.5
print('#'*10)
print(arr)
print('#'*10)

print(arr[np.abs(arr - value).argmin()]) 
# if we want to use the same function for nD array (1D, 2D, 3D) we can use the same logic with arr.flat[] instead of arr[]
# the code first subtract the "value" from all the "arr" elements ... the closest element in the "arr" to the "value" will have the minimum subtraction value
#   by argmin we get the index of that subtraction value (instead of the opposite that happens with min())

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)
##########
[0.96793926 0.96067216 0.51253235 0.77496787 0.11095917 0.11797873
 0.16902624 0.32337808 0.82468781 0.31306399]
##########
0.5125323536887663


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [106]:
hint(62)
print('#'*10)
a = np.random.rand(1,3)
b = np.random.rand(3,1)
print(a,b)
sum =0
for i in np.nditer(a):
    sum += i
print(sum)
print('#'*10)
answer(62)

hint: np.nditer
##########
[[0.38087728 0.238762   0.97962757]] [[0.51699392]
 [0.11765182]
 [0.62240849]]
1.5992668474513876
##########
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class arr:
    name: int

answer(63)

class arr2(np.ndarray):
    def __new__():
        pass


class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [128]:
# I think the questions asks about making two random int arrays then 
#   add one two each element after reindexing the first array by a second array.

a = np.ones(10)
b = np.random.randint(0,len(a),10)
c = np.random.randint(0,len(a),10)

# a.index_by(b)

answer(64)
# what actually the question is asking about is: extracting the (index:frequency) values from a random array then adding one two them (these indicies).


# that is my solution: 
d = np.bincount(b, minlength=10)
print(d+1.0)
print('#'*10)

# another solution:
d = np.bincount(b, minlength=10) # By default, numpy.bincount creates an output array with a length of one more than the maximum value in your input array. The minlength parameter is useful when you need the output to be a specific size, regardless of the values in your input 
print(d+a)
print('#'*10)

# another:
np.add.at(a, b, 1)
print(a)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)
[1. 2. 2. 2. 2. 2. 3. 1. 3. 2.]
##########
[1. 2. 2. 2. 2. 2. 3. 1. 3. 2.]
##########
[1. 2. 2. 2. 2. 2. 3. 1. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
x = np.random.randint(0,10,10)
f = np.ones(10)
l = np.random.randint(0,10,10)

print('x:', x)
print('f:', f)
print('l: ', l)

print('#'*10)

f[l] += x # if I have two indicies in (l) with the same value it takes the last one of them not both .. that's wrong.

print(f)
print('#'*10)

answer(65)
print('#'*10)

print(1.0 + np.bincount(l, weights=x)) # now that's correct!
# what have happened here is that each time an element (e) appears in the array (l), it's counted as one "custom weight" not "1" as the normal way.
# by doing so: we found ourselves with an array that in position (0) for example have not the number of times the element (0) occured in (l) only but: the number of times it appeared * its value in x.
# this will force elements of (x) to appear in their correct position in (l) and if they appeared multiple times in (l) the result array will accumulate the values of each (x) in its correct position.

x: [5 9 3 7 5 3 2 1 1 1]
f: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
l:  [2 2 7 1 7 3 0 5 9 6]
##########
[ 3.  8. 10.  4.  1.  2.  2.  6.  1.  2.]
##########
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)
##########
[ 3.  8. 15.  4.  1.  2.  2.  9.  1.  2.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [161]:
# ???
# I think: 255 * 255 * 255.

# no the question asks about if I have a real image with the 3D representation: (weight, height, 3 "for colors") how to know the unique combinations of colors available.
image = np.random.randint(0,255, size=[100,10,3], dtype=np.ubyte)

# the first solution by deepseek:
#   reshape -> calculate unique colors/rows -> len
pixels = image.reshape(-1, 3) # Reshape to (w*h, 3)
unique_colors = np.unique(pixels, axis=0) # Find unique colors/rows
number_of_unique_colors = len(unique_colors)

print(f"The image has {number_of_unique_colors} unique colors.")

# an efficient solution by deepseek:
#   reshape -> convert to void -> unique -> len
pixels = image.reshape(-1, 3)
void_view = np.ascontiguousarray(pixels).view(np.dtype((np.void, pixels.dtype.itemsize * pixels.shape[1])))
unique_colors = np.unique(void_view)

print('from void: ', len(unique_colors))
print('#'*10)

answer(66)
print('#'*10)


w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8) # all the possible values in the 3 channels are just 4 ... which makes all possible combinations: 4 * 4 * 4= 64 -> this makes validating the answer easier.

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# how to previous line works?: 
    # [1, 256, 65536] are powers of 256: 256⁰, 256¹, 256²
    # Each RGB triple [R, G, B] becomes: R×1 + G×256 + B×65536
    # This packs the 3 bytes into one 24-bit integer
    # finally np.dot produces one answer by adding all the (multiplied results) together: a1*b1 + a2*b2 + ... an*bn



# Count unique colours
n = len(np.unique(I24))
print(n)

The image has 1000 unique colors.
from void:  1000
##########
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)
##########
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)