# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [158]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [159]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) !

In [160]:
print(np.__version__)
print(np.__config__)
np.show_config # XXXXXXXXXXXXXXXXXXXXXX
# what is the difference between show_config, __config__ ?
hint(2)

2.3.3
<module 'numpy.__config__' from '/home/abdulrahman/code/numpy_practice/.venv/lib/python3.12/site-packages/numpy/__config__.py'>
hint: np.__version__, np.show_config)


#### 3. Create a null vector of size 10 (★☆☆)

In [161]:
print(np.zeros(10))
hint(3)
answer(3)

# isn't it called a null vector? why it contains a number 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
hint: np.zeros
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆) !

In [162]:
print(np.zeros(10).size) # XXXXXXXXXXXXXXXXX - this is not in "Memory"
answer(4)

print(np.zeros(10).size * np.zeros(10).itemsize)
print(np.zeros(10).nbytes)

10
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

# Simpler alternative
print("%d bytes" % Z.nbytes)
80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆) !

In [163]:
print(np.add.__doc__) # XXXXXXXXXXXX - not in Bash
answer(5)

# !python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [164]:
vec = np.zeros(10)
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [165]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆) !

In [166]:
# vec[-1:0:-1] # where is the first element ?! # XXXXXXXXX

vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [167]:
vec = np.arange(9).reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) !

In [168]:
# vec = np.array([1,2,0,0,4,0])
# vec[vec != 0] # XXXXXXXXXXXXX -> this will get the values themselves not the indices

np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) !

In [169]:
np.identity(3) # also: np.eye(N, M=None, k=0, dtype=None) -> it's more versatile
# N = rows, M = cols, k = diagonal position.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [170]:
np.random.randn(3,3,3)

array([[[-1.86725716, -0.70824862,  0.24398051],
        [ 0.06863264, -1.13789031,  0.84257019],
        [ 1.23057598, -0.57668813,  1.70612072]],

       [[ 0.01252013,  0.62613309,  0.31398681],
        [-1.13046097,  1.17755954, -1.0847294 ],
        [-0.93588453,  0.37492124,  1.42158346]],

       [[-0.01462117,  1.34260267,  1.61518624],
        [ 0.7084179 ,  0.45672191,  1.08026134],
        [-1.37038755, -0.94203986, -0.57073591]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [171]:
vec = np.random.randn(10,10)
print(vec)
print(vec.max(), vec.min())

[[ 0.39664005  2.78999909  1.78931022 -0.71359416  0.28722791  0.43047904
  -0.23343299  0.36995572  0.86050643 -0.26503897]
 [ 1.85585782 -0.13477841 -0.50749932 -0.56940077 -1.85140387  0.54143666
   1.36521339 -0.42836879 -0.16316259  0.25510923]
 [ 0.35176119 -0.97199249  0.15936945 -0.75890022 -0.63347464  0.52770526
  -1.62267661 -1.34076024  0.96322887  0.95073576]
 [-0.34224288  1.27647395  2.02941511  2.01909626  1.01711186  3.15055335
   1.54007895 -0.2237936  -0.08932185 -0.07091125]
 [-0.9742187  -0.74442924  0.78038885 -0.82070564 -0.34578092  1.57976923
  -0.81165852  1.52654236  0.40699957  0.69098633]
 [ 0.10878182  2.09884032 -0.18317957  0.20224352  1.19452799  0.94255314
  -0.24745903  1.42171095 -0.46937669 -1.61217546]
 [-1.16255871 -1.32223792  0.16052734  0.65875666 -0.62688426 -1.64508661
  -0.18559163  0.8910155  -0.10163003 -0.62057038]
 [ 1.04464056 -0.74426279 -0.72841638  0.79690647  0.6756117   0.06481645
  -0.12304108  0.70199055  1.05529725  1.05900925]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [172]:
np.random.randn(30).mean()

np.float64(0.11249795004340155)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) !

In [173]:
vec = np.ones([10,10])

vec[1:-1,1:-1] = 0

vec

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) !

In [174]:
# ??

vec = np.ones([10,10])
vec = np.pad(vec, pad_width=1, mode='constant', constant_values=[0])
vec

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) !
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [175]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) !

In [176]:
vec = np.zeros([5,5])

vec[4,0:4] = [1,2,3,4]

vec

# another solution: 
np.diag(1+np.arange(4), k=-1) 
# 1. this first creates a diagonal below the original one (at k=0) 
# 2. the content of it is [1,2,3,4] which is equal to (1 + np.arange(4))
# 3. the size of the array is (5*5) because the diagonal we created at (k=-1) have 4 elements so the original one will have 5 elements
# 4. the rest of the elements are zero default

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) ! 

In [177]:
# ??
vec = np.zeros([8,8])
vec[1::2, ::2] = 1
vec[::2, 1::2] = 1

vec


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [178]:
vec = np.zeros([6,7,8])

flat = vec.flatten()

flat[99] = 6

vec = flat.reshape(6,7,8)

np.where(vec == 6)


# another solution: 
np.unravel_index(99,(6,7,8)) # finding the corresponding index to a flat index in a multidimensional shape.

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [179]:
np.tile([0,1], [8,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [180]:
val = np.random.randn(5,5)

print((val - val.min())/(val.max() - val.min()) )

[[0.75447217 0.74704469 0.99043461 1.         0.46147978]
 [0.17707119 0.52705302 0.65143674 0.6002939  0.62734435]
 [0.28464155 0.44529774 0.55844863 0.48622937 0.70732836]
 [0.36222715 0.65077673 0.77806816 0.40544921 0.02784758]
 [0.         0.57028174 0.65912874 0.90390336 0.15339291]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [181]:
# !
color = np.dtype([
    ('R', 'u1'),
    ('G', 'uint8'),
    ('B', 'uint8'),
    ('A', 'uint8')
])
# u1 = uint8

colors = np.empty(3, dtype=color)

colors

array([(72, 135, 100, 53), ( 0,   0,   0,  0), ( 0,   0,   0,  0)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [182]:
val = np.random.randint(1,10, [5,3]) 
val2 = np.random.randint(1,10, [3,2])

print(val)

print(val2)

val @ val2 #!

[[7 4 4]
 [9 7 3]
 [8 4 4]
 [6 4 2]
 [7 2 1]]
[[8 5]
 [6 5]
 [6 7]]


array([[104,  83],
       [132, 101],
       [112,  88],
       [ 84,  64],
       [ 74,  52]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [183]:
val = np.arange(10)

val[4:8] = 10 - val[4:8]

val

# answer(25)
# # Author: Evgeni Burovski

# Z = np.arange(11)
# Z[(3 < Z) & (Z < 8)] *= -1 # !
# print(Z)

array([0, 1, 2, 3, 6, 5, 4, 3, 8, 9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [184]:
14 # !
15 # !

15

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [185]:
# !

I = 3
2 << I >> 2
I <- I # = I < - I

answer(27)
Z = 3
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
27
4
False
3j
3.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [186]:
# !
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [187]:
answer(29) # I don't understand the first answer

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [188]:
answer(30) # ok !

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# with np.errstate(all="ignore"): # ! (that's a context manager)
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# I think so.

np.sqrt(-1) == np.emath.sqrt(-1)

# it's wrong ! why?

# np.sqrt(-1) # floating number output (nan)
# np.emath.sqrt(-1) # complex number output (1j)


# 🧮 What is numpy.lib.scimath?
# The module is officially called numpy.lib.scimath. It's often imported under the convenient alias np.emath. Its purpose is to provide versions of mathematical functions that behave more usefully when dealing with complex numbers than the standard NumPy functions.

# The key difference is in how they handle inputs that would be invalid for real numbers. For example, what should the function do if you try to take the square root of a negative number?

np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [215]:
np.datetime64('now') # wow that's correct !
np.datetime64('now') - np.timedelta64(1,'D') # yesterday
np.datetime64('now') + np.timedelta64(1,'D') # tomorrow

np.datetime64('2025-09-26T12:12:34')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
first = np.datetime64('2016-07-01')
while np.datetime64(first, 'M').astype(int) % 12 + 1 == 7:
    print(first)
    first+=np.timedelta64(1,'D')

answer(34)

dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]') # the 'D' symbol is important here.
print(dates)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

[ True  True  True  True  True  True  True  True  True  True]
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)